model: '/home/lucas-fontoura/Documents/yolo-drone/runs/bage_reanotated/experiment_24/weights/best.pt'
epochs: 100
imgsz: 640
device: 'cuda'
batch: 16
seed: 42
project: 'runs/bage_reanotated'
name: 'experiment_2'